services:
  - type: web
    name: bflashcards-backend
    runtime: node
    region: oregon # ou sua região preferida
    plan: free # ou starter/standard
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && node dist/server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bflashcards-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3333
